(() => {
'use strict';
const requested=new URLSearchParams(location.search).get('install')==='web';
const C={
 en:{title:'Install Memory Game',desc:'Install Memory Game as a Web App for quick access from your device.',checking:'Checking whether your browser can offer the install dialog…',ready:'Ready to install.',installed:'Memory Game is already installed.',unavailable:'Automatic installation is not available here right now. Continue in the browser or use your browser menu to install the Web App.',install:'Install Web App',cont:'Continue in browser'},
 hr:{title:'Instaliraj Memory Game',desc:'Instaliraj Memory Game kao Web App za brzi pristup s uređaja.',checking:'Provjerava se može li preglednik ponuditi dijalog za instalaciju…',ready:'Spremno za instalaciju.',installed:'Memory Game je već instaliran.',unavailable:'Automatska instalacija trenutačno nije dostupna. Nastavi u pregledniku ili instaliraj Web App iz izbornika preglednika.',install:'Instaliraj Web App',cont:'Nastavi u pregledniku'},
 de:{title:'Memory Game installieren',desc:'Installiere Memory Game als Web App für schnellen Zugriff auf deinem Gerät.',checking:'Es wird geprüft, ob der Browser den Installationsdialog anbieten kann…',ready:'Bereit zur Installation.',installed:'Memory Game ist bereits installiert.',unavailable:'Die automatische Installation ist derzeit nicht verfügbar. Du kannst im Browser fortfahren oder die Web App über das Browsermenü installieren.',install:'Web App installieren',cont:'Im Browser fortfahren'},
 it:{title:'Installa Memory Game',desc:'Installa Memory Game come Web App per accedervi rapidamente dal dispositivo.',checking:'Verifica della disponibilità della finestra di installazione del browser…',ready:'Pronto per l’installazione.',installed:'Memory Game è già installato.',unavailable:'L’installazione automatica non è disponibile al momento. Puoi continuare nel browser o installare la Web App dal menu del browser.',install:'Installa Web App',cont:'Continua nel browser'},
 es:{title:'Instalar Memory Game',desc:'Instala Memory Game como Web App para acceder rápidamente desde tu dispositivo.',checking:'Comprobando si el navegador puede ofrecer el diálogo de instalación…',ready:'Listo para instalar.',installed:'Memory Game ya está instalado.',unavailable:'La instalación automática no está disponible ahora. Puedes continuar en el navegador o instalar la Web App desde el menú del navegador.',install:'Instalar Web App',cont:'Continuar en el navegador'}
};
let promptEvent=null,dismissed=false,installed=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true,state=installed?'installed':'checking',timer=0,panel=null,status=null,installBtn=null,continueBtn=null;
const lang=()=>{const x=(document.documentElement.lang||'en').toLowerCase().split('-')[0];return C[x]?x:'en';};
function strip(){try{const u=new URL(location.href);u.searchParams.delete('install');history.replaceState(history.state,'',u.pathname+(u.search||'')+u.hash);}catch{}}
function top(){if(!panel)return;if(matchMedia('(max-width:590px)').matches){const h=document.querySelector('.topbar');panel.style.setProperty('--install-top',Math.max(70,Math.ceil(h?.getBoundingClientRect().bottom||60)+10)+'px');}else panel.style.removeProperty('--install-top');}
function ensure(){if(panel||!requested||dismissed)return;const s=document.createElement('style');s.id='ag-web-install-style';s.textContent=`
.web-install-banner{position:fixed;left:50%;top:max(18px,env(safe-area-inset-top));transform:translateX(-50%);z-index:25;width:min(410px,calc(100vw - 24px));padding:16px;border:1px solid var(--border);border-radius:18px;background:var(--panel-2);color:var(--text);box-shadow:var(--shadow);backdrop-filter:blur(18px)}
.web-install-head{display:grid;grid-template-columns:48px 1fr;gap:12px;align-items:center}.web-install-icon{width:48px;height:48px;border-radius:13px}.web-install-title{margin:0;font-size:17px;font-weight:900}.web-install-description{margin:4px 0 0;color:var(--muted);font-size:13px;line-height:1.4}.web-install-status{margin:12px 0;padding:10px 11px;border:1px solid var(--border);border-radius:12px;background:var(--control-bg);color:var(--muted);font-size:13px}.web-install-actions{display:grid;grid-template-columns:1fr 1fr;gap:9px}.web-install-actions button{min-height:44px;border-radius:12px;padding:9px 12px;font:inherit;font-weight:850}.web-install-primary{border:0;background:linear-gradient(90deg,#31bfe9,#7869f5);color:#fff}.web-install-secondary{background:var(--control-bg);color:var(--text);border:1px solid var(--border)}.web-install-actions button:disabled{opacity:.55}.web-install-actions button:focus-visible{outline:3px solid var(--accent);outline-offset:3px}@media(max-width:590px){.web-install-banner{top:var(--install-top,70px);width:calc(100vw - 20px);padding:14px}.web-install-actions{grid-template-columns:1fr}}
`;document.head.appendChild(s);panel=document.createElement('section');panel.className='web-install-banner';panel.setAttribute('role','region');panel.setAttribute('aria-labelledby','agInstallTitle');panel.innerHTML='<div class="web-install-head"><img class="web-install-icon" src="./icon.svg" alt=""><div><h2 class="web-install-title" id="agInstallTitle"></h2><p class="web-install-description" id="agInstallDescription"></p></div></div><div class="web-install-status" id="agInstallStatus" role="status" aria-live="polite"></div><div class="web-install-actions"><button class="web-install-primary" id="agInstallButton" type="button"></button><button class="web-install-secondary" id="agInstallContinue" type="button"></button></div>';document.body.appendChild(panel);status=panel.querySelector('#agInstallStatus');installBtn=panel.querySelector('#agInstallButton');continueBtn=panel.querySelector('#agInstallContinue');
 installBtn.addEventListener('click',async()=>{if(!promptEvent||installed)return;installBtn.disabled=true;try{await promptEvent.prompt();const c=await promptEvent.userChoice;promptEvent=null;state=c?.outcome==='accepted'?'checking':'unavailable';}catch{state='unavailable';}render();});
 continueBtn.addEventListener('click',()=>{dismissed=true;strip();if(timer)clearTimeout(timer);panel.remove();panel=null;document.getElementById('ag-web-install-style')?.remove();});top();}
function render(){if(!requested||dismissed)return;ensure();if(!panel)return;const t=C[lang()];panel.querySelector('#agInstallTitle').textContent=t.title;panel.querySelector('#agInstallDescription').textContent=t.desc;installBtn.textContent=t.install;continueBtn.textContent=t.cont;if(installed||state==='installed'){status.textContent=t.installed;installBtn.hidden=true;installBtn.disabled=true;}else if(state==='ready'&&promptEvent){status.textContent=t.ready;installBtn.hidden=false;installBtn.disabled=false;}else if(state==='unavailable'){status.textContent=t.unavailable;installBtn.hidden=false;installBtn.disabled=true;}else{status.textContent=t.checking;installBtn.hidden=false;installBtn.disabled=true;}top();}
addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e;state='ready';if(timer)clearTimeout(timer);render();});addEventListener('appinstalled',()=>{installed=true;state='installed';promptEvent=null;render();});addEventListener('resize',top);document.getElementById('languageSelect')?.addEventListener('change',()=>setTimeout(render,0));new MutationObserver(render).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
if('serviceWorker'in navigator&&(location.protocol==='https:'||['localhost','127.0.0.1'].includes(location.hostname)))addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(e=>console.warn('Memory Game service worker registration failed.',e)));
if(requested){ensure();render();if(!installed)timer=setTimeout(()=>{if(!promptEvent){state='unavailable';render();}},1600);}
})();